# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Sobre mi"
  url = "#about"
  weight = 10

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 20

[[main]]
  identifier = "docencia"
  name = "Docencia"
  weight = 30

[[main]]
  identifier = "analisis"
  parent = "docencia"
  name = "Análisis"
  url = "docencia/analisis/"
  weight = 31


[[main]]
  identifier = "calculo"
  parent = "docencia"
  name = "Cálculo"
  url = "docencia/calculo/"
  weight = 32

[[main]]
  identifier = "estadistica"
  parent = "docencia"
  name = "Estadística"
  url = "docencia/estadistica/"
  weight = 33

  [[main]]
  identifier = "geogebra"
  parent = "docencia"
  name = "Geogebra"
  url = "docencia/geogebra/"
  weight = 34

[[main]]
  identifier = "git"
  parent = "docencia"
  name = "Git"
  url = "docencia/git/"
  weight = 35

[[main]]
  identifier = "julia"
  parent = "docencia"
  name = "Julia"
  url = "docencia/julia/"
  weight = 36

[[main]]
  identifier = "latex"
  parent = "docencia"
  name = "LaTeX"
  url = "docencia/latex/"
  weight = 37

[[main]]
  identifier = "python"
  parent = "docencia"
  name = "Python"
  url = "docencia/python/"
  weight = 38

[[main]]
  identifier = "r"
  parent = "docencia"
  name = "R"
  url = "docencia/r/"
  weight = 39

[[main]]
  identifier = "spss"
  parent = "docencia"
  name = "SPSS"
  url = "docencia/spss/"
  weight = 40

[[main]]
  name = "Proyectos"
  url = "#projects"
  weight = 50

[[main]]
  name = "Publicaciones"
  url = "#featured"
  weight = 60

[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
